### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by BrewerZS** [PageGuo/NewPagedFlowView#14]
时不时的错误，内存溢出的错误，以下是错误列表 1，-[_CTNativeGlyphStorage flowView:cellForPageAtIndex:]: unrecognized selector sent to instance 0x101634ad0
(null)
2，Application received signal SIGSEGV

**Comment by PageGuo** [comment]
你根据看demo里的使用方法了吗？

**Comment by wunshine** [comment]
我老是蹦到这里 cell = [_dataSource flowView:self cellForPageAtIndex:pageIndex % self.orginPageCount];
