### ISSUE TITLE
在iOS10 上偶尔会出现高度错乱的问题

### ISSUE THREAD

**Issue by NengQuan** [PageGuo/NewPagedFlowView#15]
![img_1877](https://cloud.githubusercontent.com/assets/15306400/19992653/ac8fdac0-a27a-11e6-80ca-0abb084d1a1b.JPG)

出现的频率比较少，偶尔会出现

**Comment by PageGuo** [comment]
你用在cell里?

**Comment by NengQuan** [comment]
对啊

**Comment by PageGuo** [comment]
请加我QQ,说明详细情况
