### ISSUE TITLE
将NewPagedFlowView设置为tableView的tableHeaderView，均显示不正常

### ISSUE THREAD

**Issue by Hockly** [PageGuo/NewPagedFlowView#18]
self.tableView.tableHeaderView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, Width, 250)]; [self.tableView.tableHeaderView addSubview:pageFlowView];
或者
self.tableView.tableHeaderView = pageFlowView;
或者
UIScrollView *bottomScrollView = [[UIScrollView alloc] initWithFrame:CGRectMake(0, 0, ZRScreenW, (ZRScreenW - 84) * 9 / 16 + 24)];
 [pageFlowView reloadData];
 [bottomScrollView addSubview:pageFlowView];
 self.tableView.tableHeaderView = bottomScrollView;

**Comment by PageGuo** [comment]
加我好友说

**Comment by Hockly** [comment]
加了 780871012是我

**Comment by Hockly** [comment]
是我大意了，没有看到还有个设置sizeForPageInFlowView这个代理方法，非常感谢
