### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by zhangwei5436** [PageGuo/NewPagedFlowView#19]
轮播图在首页出现 ，在5s 上面 如果连续使用APP 1个小时 左右  或者停留在这个页面 首页这个页面 不动 也是1个小时左右，人为的反向滑动 或者 正向滑动轮播图，会出现 卡顿的情况，或者 划不动的情况  在6p 或者 7 上目前出现这种情况的概率 ，很小   现在项目里用的是最新的 框架。。

**Comment by PageGuo** [comment]
连续使用App,离开当前页建议调用stopTimer

**Comment by zhangwei5436** [comment]
当前页是首页啊  如果离开这个页面的时候 关闭了定时器  重新回到首页  不是又要开起定时器 吗？？

**Comment by PageGuo** [comment]
严格来说应该暂停,你项目中如果用的定时器多的话,有可能会影响。自己检查一下吧,多看一些项目,如果有问题qq我,别总在这里评论了哈。

**Comment by PageGuo** [comment]
....
