### ISSUE TITLE
只有一张图片时有bug

### ISSUE THREAD

**Issue by xipi000** [PageGuo/NewPagedFlowView#2]
只有一张图片时候，循环滚动有bug，会滚没了！希望一张图片时，关闭定时器，不要滚动！
还有能否添加给功能：非当前页可以设置显示大小，比如跟当前页一样大小（之间有间距）。
minimumPageScale属性设置很小的时候（0.1）当前页显示不正常，时大时小。

**Comment by PageGuo** [comment]
已经解决了,请更新

**Comment by xipi000** [comment]
谢谢！
我刚刚试了一下，minimumPageScale改为0.1的时候，当前页显示仍然不正常，时大时小。
非当前页的大小能自己调整吗？
