### ISSUE TITLE
内存不能释放的问题

### ISSUE THREAD

**Issue by wownbafifa** [PageGuo/NewPagedFlowView#23]
你好，这个轮播无论是自动轮播还是手动轮播，内存一直在增长。如果首页使用这个轮播，放一会就会卡的APP使用不了。。。。

**Comment by wownbafifa** [comment]
很神奇，模拟器、真机5S、5C上面内存稳定，6S、7上面内存一直在涨。。。

**Comment by PageGuo** [comment]
你可以邮件联系我的,不要一直这里留言好吗
