### ISSUE TITLE
紧急需求

### ISSUE THREAD

**Issue by hegelsu** [PageGuo/NewPagedFlowView#30]
能否在代理里把用户点击的位置也传进去，广告统计方要求传入点击的位置。。。

- (void)didSelectCell:(PGIndexBannerSubiew *)subView withSubViewIndex:(NSInteger)subIndex;

实现点击的CGPoint

**Comment by PageGuo** [comment]
你根据自己的需求去改啊

**Comment by hegelsu** [comment]
已改，谢谢作者，想让作者加是想后面如果有更新能更好的升级。再次感谢。
