### ISSUE TITLE
使用方法，还是太多了，不够简便

### ISSUE THREAD

**Issue by CCBrother** [PageGuo/NewPagedFlowView#52]
可以参考下SDCycleScrollView

**Comment by CCBrother** [comment]
pageControl和PGIndexBannerSubiew 能不能放到内部去创建

**Comment by PageGuo** [comment]
SDCycleScrollView只是一个简单的轮播ok?不放到内部创建的原因是方便自定义。不够简便可以不用，空闲的时候我会进行重构。

**Comment by CCBrother** [comment]
不好意思，打扰了
