### ISSUE TITLE
reloadData bug

### ISSUE THREAD

**Issue by zliuqing** [PageGuo/NewPagedFlowView#6]
调用reloadData会引起某两页连接在一起，并有叠加的问题。例如在demo viewDidLoad 中加入：
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(15.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [pageFlowView reloadData];
    });

**Comment by PageGuo** [comment]
已经解决了,请同学更新一下.

**Comment by mokai** [comment]
@PageGuo 目前在UICollectionView中使用NewPagedFlowView作为Header，下拉时进行第二次reloadData也会发生两页连接在一起重叠的问题
