### ISSUE TITLE
如果将此轮播器添加在一个以scrollView为父类的view上,滑动外部则内部轮播器将会出现UI卡的现象

### ISSUE THREAD

**Issue by zhaiyuhao** [PageGuo/NewPagedFlowView#8]
添加一句话: 
 [[NSRunLoop mainRunLoop] addTimer:self.timer forMode:NSRunLoopCommonModes];

- (void)startTimer {
    if (self.orginPageCount > 1 && self.isOpenAutoScroll) {
        self.timer = [NSTimer scheduledTimerWithTimeInterval:self.autoTime target:self selector:@selector(autoNextPage) userInfo:nil repeats:YES];
        [[NSRunLoop mainRunLoop] addTimer:self.timer forMode:NSRunLoopCommonModes];
    }
}

**Comment by PageGuo** [comment]
这个和项目的需求相关，当时我项目里要求的是滚动时轮播图不要动。

**Comment by zhangwei5436** [comment]
？？ 怎么解决啊？？？

**Comment by PageGuo** [comment]
解决了啊!!!!
